GARNAME           = perl-Class-Load
GARVERSION        = 0.25
MASTER_SITES      = https://cpan.metacpan.org/authors/id/E/ET/ETHER/
DEPENDS           = perl/perl-Class-Singleton perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
