GARNAME           = perl-DateTime
GARVERSION        = 1.19
MASTER_SITES      = https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/
PERL_MODULE_STYLE = Build.PL
DEPENDS           = perl/perl-DateTime-Locale perl/perl-DateTime-TimeZone perl/perl-Math-Round perl/perl-Params-Validate
BUILDDEPS         = perl/perl-Test-Exception

include ../../perl/perl/perl-module.mk
