GARNAME      = perl-DateTime-Format-ISO8601
GARVERSION   = 0.08
MASTER_SITES = https://cpan.metacpan.org/authors/id/J/JH/JHOBLITT/
DEPENDS      = perl/perl-DateTime perl/perl-DateTime-Format-Builder perl/perl-Exporter-Tiny
#PERL_MODULE_STYLE = Build.PL

include ../../perl/perl/perl-module.mk
