GARNAME = gcc-target
CATEGORIES = gcc-target
GARVERSION = none
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	gcc-target/binutils \
	gcc-target/gcc \
	gcc-target/gcc-wrappers

GAR_EXTRA_CONF += gcc-target/gcc-target/toolchain.mk
include ../../gar.mk
