GCC_MAJOR_VERSION = 9
GCC_MINOR_VERSION = 2
GCC_TEENY_VERSION = 0
GCC_EXTRA_VERSION =

GCC_VERSION = $(strip $(if $(GCC_EXTRA_VERSION), \
	$(if $(filter RC-%,$(GCC_EXTRA_VERSION)), \
		$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)-$(GCC_EXTRA_VERSION), \
		$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION)-$(GCC_EXTRA_VERSION)                       ), \
	$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)  ))

CROSS_GCC_DIR = \
	$(gcc_build_DESTDIR)$(gcc_build_libdir)/gcc/$(GARTARGET)
CROSS_GCC_LIBDIR = \
	$(CROSS_GCC_DIR)/$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)
CROSS_GCC_INCLUDEDIR = \
	$(CROSS_GCC_LIBDIR)/include
CROSS_GCC_LIBEXECDIR = \
	$(gcc_build_DESTDIR)$(gcc_build_libexecdir)/gcc/$(GARTARGET)/$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)

BINUTILS_VERSION = 2.33.1
GMP_VERSION = 6.2.0
# ISL 0.22.1 fails to build when used as part of GCC 9.3.0
ISL_VERSION = 0.21
MPC_VERSION = 1.1.0
MPFR_VERSION = 4.0.2
