GARNAME = toolchain-main
VERSION =
CATEGORIES = toolchain-main
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	toolchain-main/linux-headers \
	toolchain-main/musl \
	toolchain-main/compiler-rt \
	toolchain-main/libunwind  \
	toolchain-main/libcxxabi \
	toolchain-main/libcxx \
	toolchain-main/clang-wrappers \
	toolchain-main/binutils \
	toolchain-main/gcc \
	toolchain-main/gcc-wrappers

include ../../gar.mk
