GARNAME      = perl-Parse-Yapp
GARVERSION   = 1.21
MASTER_SITES = https://cpan.metacpan.org/authors/id/W/WB/WBRASWELL/
DEPENDS      = perl/perl-Date-Manip perl/perl-libwww-perl perl/perl-XML-DOM perl/perl-XML-Parser

include ../../perl/perl/perl-module.mk
