GARNAME      = perl-CPAN-Meta-Requirements
GARVERSION   = 2.140
MASTER_SITES = https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/
DEPENDS      = perl/perl-CPAN-Meta

include ../../perl/perl/perl-module.mk
