GARNAME        = perl-DBD-mysql
GARVERSION     = 4.050
MASTER_SITES   = https://cpan.metacpan.org/authors/id/D/DV/DVEEDEN/
DEPENDS        = db/mariadb perl/perl-DBI
PERL_MODULE_SO = true

include ../../perl/perl/perl-module.mk
