GARNAME      = perl-DateTime-TimeZone
GARVERSION   = 1.90
MASTER_SITES = https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Class-Load perl/perl-Class-Singleton perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
