GARNAME = toolchain-build-gcc
VERSION =
CATEGORIES = toolchain-build-gcc
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	toolchain-build-gcc/gcc \
	toolchain-build-gcc/gcc-wrappers

include ../../gar.mk
