PYTHON2_VERSION_MAJOR = 2
PYTHON2_VERSION_MINOR = 7
PYTHON2_VERSION_TEENY = 17
PYTHON2_VERSION = $(PYTHON2_VERSION_MAJOR).$(PYTHON2_VERSION_MINOR).$(PYTHON2_VERSION_TEENY)

PYTHON2_includedir = $(includedir)/python$(PYTHON2_VERSION_MAJOR).$(PYTHON2_VERSION_MINOR)
PYTHON2_libdir = $(libdir)/python$(PYTHON2_VERSION_MAJOR).$(PYTHON2_VERSION_MINOR)
build_PYTHON2_includedir = $(build_includedir)/python$(PYTHON2_VERSION_MAJOR).$(PYTHON2_VERSION_MINOR)
build_PYTHON2_libdir = $(build_libdir)/python$(PYTHON2_VERSION_MAJOR).$(PYTHON2_VERSION_MINOR)
