GARNAME      = perl-Module-Implementation
GARVERSION   = 0.06
MASTER_SITES = https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Module-Runtime perl/perl-Try-Tiny

include ../../perl/perl/perl-module.mk
