GARNAME = libc-crt
GARVERSION =
CATEGORIES = tainted-build
SOURCEPKG = toolchain/libc-crt
LICENSE =

DESCRIPTION =
define BLURB
endef

INSTALL_SCRIPTS = libs

GAR_EXTRA_CONF += tainted-build/tainted-build/toolchain.mk
GAR_EXTRA_CONF += toolchain/libc-crt/package-api.mk
include ../../gar.mk
