PYTHON3_VERSION_MAJOR = 3
PYTHON3_VERSION_MINOR = 8
PYTHON3_VERSION_TEENY = 2
PYTHON3_VERSION = $(PYTHON3_VERSION_MAJOR).$(PYTHON3_VERSION_MINOR).$(PYTHON3_VERSION_TEENY)

PYTHON3_includedir = $(includedir)/python$(PYTHON3_VERSION_MAJOR).$(PYTHON3_VERSION_MINOR)
PYTHON3_libdir = $(libdir)/python$(PYTHON3_VERSION_MAJOR).$(PYTHON3_VERSION_MINOR)
build_PYTHON3_includedir = $(build_includedir)/python$(PYTHON3_VERSION_MAJOR).$(PYTHON3_VERSION_MINOR)
build_PYTHON3_libdir = $(build_libdir)/python$(PYTHON3_VERSION_MAJOR).$(PYTHON3_VERSION_MINOR)
