GARNAME             = perl-List-MoreUtils
GARVERSION          = 0.428
MASTER_SITES        = https://cpan.metacpan.org/authors/id/R/RE/REHSACK/
#PERL_MODULE_PATCHES = gar.patch
PERL_MODULE_SO      = true
DEPENDS             = perl/perl-Exporter-Tiny

include ../../perl/perl/perl-module.mk
