GARNAME = libc-crt
GARVERSION =
CATEGORIES = toolchain-dirty
SOURCEPKG = toolchain/libc-crt
LICENSE =

DESCRIPTION =
define BLURB
endef

INSTALL_SCRIPTS = libs

GAR_EXTRA_CONF += toolchain-dirty/toolchain-dirty/toolchain.mk
GAR_EXTRA_CONF += toolchain/libc-crt/package-api.mk
include ../../gar.mk
