GARNAME = gcc-wrappers
GARVERSION = unknown
CATEGORIES = toolchain-wrappers
DISTFILES = \
	$(DESTIMG)-cpp \
	$(DESTIMG)-gcc \
	$(DESTIMG)-gxx \
	$(DESTIMG)-ld.bfd
LICENSE = 

DESCRIPTION =
define BLURB
endef

BUILDDEPS = toolchain/toolchain

include ../../gar.mk
