GARNAME = gcc-wrappers
GARVERSION = unknown
CATEGORIES = toolchain-wrappers
DISTFILES = \
	$(DESTIMG)-cpp \
	$(DESTIMG)-gcc \
	$(DESTIMG)-g++ \
	$(DESTIMG)-ld.bfd
LICENSE = 

DESCRIPTION =
define BLURB
endef

BUILD_SCRIPTS = wrappers
INSTALL_SCRIPTS = wrappers

BUILDDEPS = toolchain/toolchain

include ../../gar.mk
