GARNAME = toolchain-main-gcc
VERSION =
CATEGORIES = toolchain-main-gcc
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	toolchain-main-gcc/binutils \
	toolchain-main-gcc/gcc \
	toolchain-main-gcc/gcc-wrappers

include ../../gar.mk
