GARNAME           = perl-Module-Build
GARVERSION        = 0.4231
MASTER_SITES      = https://cpan.metacpan.org/authors/id/L/LE/LEONT/
PERL_MODULE_STYLE = Build.PL

include ../../perl/perl/perl-module.mk
