GARNAME           = perl-Params-Validate
GARVERSION        = 1.18
MASTER_SITES      = https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/
PERL_MODULE_STYLE = Build.PL
DEPENDS           = perl/perl-Module-Implementation

include ../../perl/perl/perl-module.mk
