GARNAME      = perl-HTTP-Daemon
GARVERSION   = 6.06
MASTER_SITES = https://cpan.metacpan.org/authors/id/O/OA/OALDERS/
DEPENDS      = perl/perl-Module-Build-Tiny

include ../../perl/perl/perl-module.mk
