GARNAME = tainted-main
CATEGORIES = tainted-main
GARVERSION = none
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	tainted-main/binutils \
	tainted-main/gcc \
	tainted-main/gcc-wrappers

GAR_EXTRA_CONF += tainted-main/tainted-main/toolchain.mk
include ../../gar.mk
