GARNAME        = perl-XML-Parser
GARVERSION     = 2.41
MASTER_SITES   = https://cpan.metacpan.org/authors/id/T/TO/TODDR/
DEPENDS        = lib/expat perl/perl-libwww-perl
PERL_MODULE_SO = true

include ../../perl/perl/perl-module.mk
