GARNAME = clang-wrappers
GARVERSION = unknown
CATEGORIES = toolchain
DISTFILES = \
	$(DESTIMG)-clang-cpp \
	$(DESTIMG)-clang \
	$(DESTIMG)-clang++ \
	$(DESTIMG)-ld.lld
LICENSE = 

DESCRIPTION =
define BLURB
endef

BUILD_SCRIPTS = wrappers
INSTALL_SCRIPTS = wrappers

include ../../gar.mk
