GARNAME = compiler-gcc
CATEGORIES = compiler-gcc
GARVERSION = none
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	compiler-gcc/binutils \
	compiler-gcc/gcc

GAR_EXTRA_CONF += compiler-gcc/compiler-gcc/toolchain.mk
include ../../gar.mk
