GARNAME      = perl-XML-DOM
GARVERSION   = 1.44
MASTER_SITES = https://cpan.metacpan.org/authors/id/T/TJ/TJMATHER/
DEPENDS      = perl/perl-libwww-perl perl/perl-libxml-perl perl/perl-XML-Parser perl/perl-XML-RegExp

include ../../perl/perl/perl-module.mk
