GARNAME = toolchain
VERSION = none
CATEGORIES = toolchain
LICENSE =

DESCRIPTION = 
define BLURB
endef

DEPENDS = \
	toolchain/libc-crt \
	toolchain/gcc-for-clang \
	toolchain/clang \
	toolchain/clang-wrappers

GAR_EXTRA_CONF += toolchain/toolchain/toolchain.mk
include ../../gar.mk
