GARNAME      = perl-SOAP-Lite
GARVERSION   = 1.0
MASTER_SITES = https://cpan.metacpan.org/authors/id/P/PH/PHRED/
DEPENDS      = perl/perl-Class-Inspector perl/perl-libwww-perl perl/perl-XML-Parser

include ../../perl/perl/perl-module.mk

CONFIGURE_ENV := echo Y | $(CONFIGURE_ENV)
