GARNAME      = perl-libwww-perl
GARVERSION   = 6.16
MASTER_SITES = https://cpan.metacpan.org/authors/id/O/OA/OALDERS/
DEPENDS      = perl/perl-HTML-Parser perl/perl-URI

include ../../perl/perl/perl-module.mk

CONFIGURE_ARGS += -n

CONFIGURE_ENV := echo N | $(CONFIGURE_ENV)
