GARNAME        = perl-HTML-Parser
GARVERSION     = 3.71
MASTER_SITES   = https://cpan.metacpan.org/authors/id/G/GA/GAAS/
DEPENDS        = perl/perl-HTML-Tagset
PERL_MODULE_SO = true

include ../../perl/perl/perl-module.mk
